@startuml
allow_mixing
database Database

package Core {
  object PresentCodecastUsecase
  class Codecast
  class User
  class License
  interface Gateway
  class MockGateway
}

PresentCodecastUsecase --> Codecast
PresentCodecastUsecase --> User
PresentCodecastUsecase --> License
PresentCodecastUsecase --> Gateway
Gateway <|-- MockGateway
MockGateway --> Database

package GUI {
}
@enduml