@startuml
package Core {
  object PresentCodecastUsecase
  class Codecast
  class User
  class License
  object Something
}

PresentCodecastUsecase --> Codecast
PresentCodecastUsecase --> User
PresentCodecastUsecase --> License
PresentCodecastUsecase --> Something
Something <-- Database

package GUI {
}

package Database {
  object Database
}
@enduml