@startuml
allow_mixing
database Database

package Core {
  class Entity
  class User
  class Codecast
  class License
  interface Gateway
  class MockGateway
  class PresentableCodecast <<DS>>
  class PresentCodecastUsecase
  interface Gatekeeper {
    ---
    + setLoginUser
  }
}

Database <-- MockGateway
PresentCodecastUsecase --> Codecast
PresentCodecastUsecase --> License
PresentCodecastUsecase --> Gateway
PresentCodecastUsecase --> User
Gateway --> Codecast
Gateway --> License
Gateway --> User
License --> Codecast
License --> User
MockGateway --|> Gateway
User --|> Entity
License --|> Entity
Codecast --|> Entity

package GUI {
  object Presenter
}

Presenter --> PresentableCodecast
PresentCodecastUsecase *.. PresentableCodecast : generate

object Session
cloud Somewhere
Somewhere --> Session
Session ..* Gatekeeper : validated
@enduml